### ISSUE TITLE
跑smiles_bpe.sh脚本并指定BBBP任务时出现"no molecule provided"报错

### ISSUE THREAD

**Issue by fangxintao** [thunlp/KV-PLM#2]
跑smiles_bpe.sh时，指定任务为BBBP，在分数据集的时候语句scaf = sp.train_valid_test_split(dataset=seq, smiles_list=sm_list, frac_train=0.8,frac_valid=0.1, frac_test=0.1, include_chirality=False)报错，错误提示为"no molecule provided"，我将数据集分成几段依次尝试，最后发现是smile data的59号句子和61号句子这里放入库函数中会出问题。想问下是否是数据集本身有问题，还是说别的原因？

**Comment by yangzhao1230** [comment]
@fangxintao 你好，我尝试跑BBBP也遇到了这个问题，请问你解决了吗？

**Comment by Greay83** [comment]
@yangzhao1230 @fangxintao 各位大佬你们好，我在运行run_molecule.py时也遇到了"no molecule provided"的报错，请问大佬们解决了吗？

**Comment by Ellenzzn** [comment]
该情况在我们处理原始数据时没有出现，可能是splitting function在后续版本迭代过程中出现了这一问题。数据集的59,61,391,614,642,645-649和685号位置会发生报错，建议直接将这些位置替换为其它合理的SMILES表达式以避免影响。
